name: Deploy React and ASP.NET API into Azure App Service

on:
  push:
    branches:
      - main

jobs:
  Include-env-file-for-API:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./todo_api_publabb2/todo_api_publabb2
    steps:
      - uses: actions/checkout@v4

      - name: test directory
        run: echo "$PWD"

      - name: Create env file for .NET API
        run: touch .env

      - name: Add variables for .NET API
        run: |
          echo ENDPOINT=${{secrets.COMOS_ENDPOINT}} >> .env
          echo KEY=${{secrets.KEY}} >> .env
          echo DATABASE=${{secrets.DATABASE}} >> .env
          echo CONTAINER=${{secrets.CONTAINER}} >> .env
  Include-env-file-for-FRONTEND:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: /todolistfrontend
    steps:
      - name: Create env file for FrontEnd
        run: touch .env

      - name: Add variables for FrontEnd
        run: |
          echo REACT_APP_ENDPOINT=${{secrets.API_ENDPOINT}}
  



