name: Deploy React and ASP.NET API into Azure App Service

on:
  push:
    branches:
      - main

jobs:
  build-API:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: azure/docker-login@v1
        with:
          login-server: docker.io/libre255
          username: ${{ secrets.D_USER_NAME}}
          password: ${{ secrets.D_PASSWORD}}

      - uses: azure/webapps-deploy@v2
        with:
          app-name: testapibv
          publish-profile: ${{ secrets.AZURE_WEBB_PUBLISH_PROFILE }}
          images: |
            docker.io/libre255/testapibrian:2.0
            docker.io/libre255/frontendlabb3:1.0