name: DeployBV

on:
  push:
    branches:
      - main
env:
  frontendImageName: libre255/todofrontend
  apiImageName: libre255/todoapi

jobs:
  buildpush-API:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./todo_api_publabb2/todo_api_publabb2
    steps:
      - uses: actions/checkout@v4

      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.D_USER_NAME}}
          password: ${{ secrets.D_PASSWORD}}
      
      - name: docker build API
        run: docker build -t ${{env.apiImageName}}:${{ github.sha}} .
  
      - name: docker push API
        run: docker push ${{env.apiImageName}}:${{ github.sha}}
      
  buildpush-FRONTEND:
    runs-on: ubuntu-latest
    needs: buildpush-API
    defaults:
      run:
        working-directory: ./todolistfrontend
    steps:
      - uses: actions/checkout@v4
      
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.D_USER_NAME}}
          password: ${{ secrets.D_PASSWORD}}

      - name: docker build Frontend
        run: docker build -t ${{env.frontendImageName}}:${{ github.sha}} .
      
      - name: docker push Frontend
        run: docker push ${{env.frontendImageName}}:${{ github.sha}}

  deployApps:
    runs-on: ubuntu-latest
    needs: buildpush-FRONTEND
    steps:
    - uses: actions/checkout@v4

    - uses: docker/login-action@v3
      with:
        username: ${{ secrets.D_USER_NAME}}
        password: ${{ secrets.D_PASSWORD}}

    - uses: azure/webapps-deploy@v2
      with:
        app-name: 'todo-frontend-bv'
        publish-profile: ${{ secrets.FRONTEND_PF }}
        images: docker.io/${{env.frontendImageName}}:${{ github.sha}}
    
    - uses: azure/webapps-deploy@v2
      with:
        app-name: 'todo-backend-bv'
        publish-profile: ${{ secrets.BACKEND_PF }}
        images: docker.io/${{env.apiImageName}}:${{ github.sha }}

    
          