name: DeployBV

on:
  push:
    branches:
      - main

jobs:
  build-API:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./todo_api_publabb2/todo_api_publabb2
    steps:
      - uses: actions/checkout@v4

      - name: Create env file for .NET API
        run: touch .env

      - name: Add variables for .NET API
        run: |
          echo ENDPOINT=${{secrets.COMOS_ENDPOINT}} >> .env
          echo KEY=${{secrets.KEY}} >> .env
          echo DATABASE=${{secrets.DATABASE}} >> .env
          echo CONTAINER=${{secrets.CONTAINER}} >> .env

      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.D_USER_NAME}}
          password: ${{ secrets.D_PASSWORD}}
      
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./todo_api_publabb2/todo_api_publabb2/Dockerfile
          push: true
          tags: docker.io/libre255/todoapi:${{ github.sha }}

  build-push-FRONTEND:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./todolistfrontend
    steps:
      - uses: actions/checkout@v4
      
      - name: Create env file for FrontEnd
        run: touch .env

      - name: Add variable for FrontEnd
        run: echo REACT_APP_ENDPOINT=${{secrets.API_ENDPOINT}} >> .env
      
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.D_USER_NAME}}
          password: ${{ secrets.D_PASSWORD}}

      - run:
          docker build -t libre255/frontendlabb3:${{ github.sha}} .
          docker push libre255/frontendlabb3:${{ github.sha}}

  # deployApps:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v4

  #   - uses: azure/docker-login@v1
  #     with:
  #       login-server: docker.io/libre255
  #       username: ${{ secrets.D_USER_NAME}}
  #       password: ${{ secrets.D_PASSWORD}}

  #   - uses: azure/webapps-deploy@v2
  #     with:
  #       app-name: 'todo-frontend-bv'
  #       publish-profile: ${{ secrets.frontend_pf }}
  #       images: docker.io/libre255/todofrontend:${{ github.sha}}
    
  #   - uses: azure/webapps-deploy@v2
  #     with:
  #       app-name: 'todo-backend-bv'
  #       publish-profile: ${{ secrets.backend_pf }}
  #       images: docker.io/libre255/todoapi:${{ github.sha }}
    
          